version: "2"
run:
  tests: true
output:
  formats:
    text:
      path: stdout
      print-linter-name: true
      print-issued-lines: true
linters:
  enable:
    - dupl
    - goconst
    - gocyclo
    - gosec
    - misspell
    - prealloc
    - revive
    - staticcheck
    - unconvert
    - unparam
  settings:
    dupl:
      threshold: 100
    errcheck:
      check-type-assertions: true
      check-blank: true
    goconst:
      min-len: 2
      min-occurrences: 2
    gocritic:
      disabled-checks:
        - unnecessaryBlock
      enabled-tags:
        - diagnostic
        - style
        - performance
    gocyclo:
      min-complexity: 15
    govet:
      disable:
        - fieldalignment
      enable-all: true
    lll:
      line-length: 120
    misspell:
      locale: US
  exclusions:
    generated: lax
    rules:
      - linters:
          - dupl
          - errcheck
          - fieldalignment
          - goconst
          - gocyclo
          - gosec
        path: _test\.go
      - linters:
          - fieldalignment
        path: .*_test\.go$|integration_test\.go$
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - ascii-art
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
